// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: manager-worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRole) Reset() {
	*x = WorkerRole{}
	mi := &file_manager_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRole) ProtoMessage() {}

func (x *WorkerRole) ProtoReflect() protoreflect.Message {
	mi := &file_manager_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRole.ProtoReflect.Descriptor instead.
func (*WorkerRole) Descriptor() ([]byte, []int) {
	return file_manager_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WorkerRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AssignWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ManagerId     string                 `protobuf:"bytes,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	ManagerRole   string                 `protobuf:"bytes,3,opt,name=manager_role,json=managerRole,proto3" json:"manager_role,omitempty"`
	WorkerRoles   []*WorkerRole          `protobuf:"bytes,4,rep,name=worker_roles,json=workerRoles,proto3" json:"worker_roles,omitempty"`
	TaskMd        string                 `protobuf:"bytes,5,opt,name=task_md,json=taskMd,proto3" json:"task_md,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignWorkersRequest) Reset() {
	*x = AssignWorkersRequest{}
	mi := &file_manager_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignWorkersRequest) ProtoMessage() {}

func (x *AssignWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignWorkersRequest.ProtoReflect.Descriptor instead.
func (*AssignWorkersRequest) Descriptor() ([]byte, []int) {
	return file_manager_worker_proto_rawDescGZIP(), []int{1}
}

func (x *AssignWorkersRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignWorkersRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AssignWorkersRequest) GetManagerRole() string {
	if x != nil {
		return x.ManagerRole
	}
	return ""
}

func (x *AssignWorkersRequest) GetWorkerRoles() []*WorkerRole {
	if x != nil {
		return x.WorkerRoles
	}
	return nil
}

func (x *AssignWorkersRequest) GetTaskMd() string {
	if x != nil {
		return x.TaskMd
	}
	return ""
}

func (x *AssignWorkersRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AssignWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Solution      []byte                 `protobuf:"bytes,3,opt,name=solution,proto3" json:"solution,omitempty"` // ZIP архив с кодом
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignWorkersResponse) Reset() {
	*x = AssignWorkersResponse{}
	mi := &file_manager_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignWorkersResponse) ProtoMessage() {}

func (x *AssignWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignWorkersResponse.ProtoReflect.Descriptor instead.
func (*AssignWorkersResponse) Descriptor() ([]byte, []int) {
	return file_manager_worker_proto_rawDescGZIP(), []int{2}
}

func (x *AssignWorkersResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignWorkersResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AssignWorkersResponse) GetSolution() []byte {
	if x != nil {
		return x.Solution
	}
	return nil
}

var File_manager_worker_proto protoreflect.FileDescriptor

const file_manager_worker_proto_rawDesc = "" +
	"\n" +
	"\x14manager-worker.proto\x12\x06worker\"B\n" +
	"\n" +
	"WorkerRole\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xc6\x02\n" +
	"\x14AssignWorkersRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\tR\tmanagerId\x12!\n" +
	"\fmanager_role\x18\x03 \x01(\tR\vmanagerRole\x125\n" +
	"\fworker_roles\x18\x04 \x03(\v2\x12.worker.WorkerRoleR\vworkerRoles\x12\x17\n" +
	"\atask_md\x18\x05 \x01(\tR\x06taskMd\x12F\n" +
	"\bmetadata\x18\x06 \x03(\v2*.worker.AssignWorkersRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x15AssignWorkersResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bsolution\x18\x03 \x01(\fR\bsolution2d\n" +
	"\rWorkerService\x12S\n" +
	"\x14AssignWorkersAndWait\x12\x1c.worker.AssignWorkersRequest\x1a\x1d.worker.AssignWorkersResponseB'Z%worker/internal/fetcher/grpc/workerpbb\x06proto3"

var (
	file_manager_worker_proto_rawDescOnce sync.Once
	file_manager_worker_proto_rawDescData []byte
)

func file_manager_worker_proto_rawDescGZIP() []byte {
	file_manager_worker_proto_rawDescOnce.Do(func() {
		file_manager_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_worker_proto_rawDesc), len(file_manager_worker_proto_rawDesc)))
	})
	return file_manager_worker_proto_rawDescData
}

var file_manager_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_manager_worker_proto_goTypes = []any{
	(*WorkerRole)(nil),            // 0: worker.WorkerRole
	(*AssignWorkersRequest)(nil),  // 1: worker.AssignWorkersRequest
	(*AssignWorkersResponse)(nil), // 2: worker.AssignWorkersResponse
	nil,                           // 3: worker.AssignWorkersRequest.MetadataEntry
}
var file_manager_worker_proto_depIdxs = []int32{
	0, // 0: worker.AssignWorkersRequest.worker_roles:type_name -> worker.WorkerRole
	3, // 1: worker.AssignWorkersRequest.metadata:type_name -> worker.AssignWorkersRequest.MetadataEntry
	1, // 2: worker.WorkerService.AssignWorkersAndWait:input_type -> worker.AssignWorkersRequest
	2, // 3: worker.WorkerService.AssignWorkersAndWait:output_type -> worker.AssignWorkersResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_manager_worker_proto_init() }
func file_manager_worker_proto_init() {
	if File_manager_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_worker_proto_rawDesc), len(file_manager_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_worker_proto_goTypes,
		DependencyIndexes: file_manager_worker_proto_depIdxs,
		MessageInfos:      file_manager_worker_proto_msgTypes,
	}.Build()
	File_manager_worker_proto = out.File
	file_manager_worker_proto_goTypes = nil
	file_manager_worker_proto_depIdxs = nil
}
