// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: boss-manager.proto

package managerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос от boss к manager
type AssignManagersRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskId               string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TechnicalDescription string                 `protobuf:"bytes,2,opt,name=technical_description,json=technicalDescription,proto3" json:"technical_description,omitempty"`
	Roles                []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AssignManagersRequest) Reset() {
	*x = AssignManagersRequest{}
	mi := &file_boss_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignManagersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignManagersRequest) ProtoMessage() {}

func (x *AssignManagersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignManagersRequest.ProtoReflect.Descriptor instead.
func (*AssignManagersRequest) Descriptor() ([]byte, []int) {
	return file_boss_manager_proto_rawDescGZIP(), []int{0}
}

func (x *AssignManagersRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignManagersRequest) GetTechnicalDescription() string {
	if x != nil {
		return x.TechnicalDescription
	}
	return ""
}

func (x *AssignManagersRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AssignManagersRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Ответ manager с ZIP архивом
type AssignManagersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Solution      []byte                 `protobuf:"bytes,4,opt,name=solution,proto3" json:"solution,omitempty"` // ZIP архив со всем проектом
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignManagersResponse) Reset() {
	*x = AssignManagersResponse{}
	mi := &file_boss_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignManagersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignManagersResponse) ProtoMessage() {}

func (x *AssignManagersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boss_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignManagersResponse.ProtoReflect.Descriptor instead.
func (*AssignManagersResponse) Descriptor() ([]byte, []int) {
	return file_boss_manager_proto_rawDescGZIP(), []int{1}
}

func (x *AssignManagersResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignManagersResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AssignManagersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AssignManagersResponse) GetSolution() []byte {
	if x != nil {
		return x.Solution
	}
	return nil
}

var File_boss_manager_proto protoreflect.FileDescriptor

const file_boss_manager_proto_rawDesc = "" +
	"\n" +
	"\x12boss-manager.proto\x12\amanager\"\x82\x02\n" +
	"\x15AssignManagersRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x123\n" +
	"\x15technical_description\x18\x02 \x01(\tR\x14technicalDescription\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12H\n" +
	"\bmetadata\x18\x04 \x03(\v2,.manager.AssignManagersRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x16AssignManagersResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bsolution\x18\x04 \x01(\fR\bsolution2j\n" +
	"\x0eManagerService\x12X\n" +
	"\x15AssignManagersAndWait\x12\x1e.manager.AssignManagersRequest\x1a\x1f.manager.AssignManagersResponseB)Z'manager/internal/fetcher/grpc/managerpbb\x06proto3"

var (
	file_boss_manager_proto_rawDescOnce sync.Once
	file_boss_manager_proto_rawDescData []byte
)

func file_boss_manager_proto_rawDescGZIP() []byte {
	file_boss_manager_proto_rawDescOnce.Do(func() {
		file_boss_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_manager_proto_rawDesc), len(file_boss_manager_proto_rawDesc)))
	})
	return file_boss_manager_proto_rawDescData
}

var file_boss_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_boss_manager_proto_goTypes = []any{
	(*AssignManagersRequest)(nil),  // 0: manager.AssignManagersRequest
	(*AssignManagersResponse)(nil), // 1: manager.AssignManagersResponse
	nil,                            // 2: manager.AssignManagersRequest.MetadataEntry
}
var file_boss_manager_proto_depIdxs = []int32{
	2, // 0: manager.AssignManagersRequest.metadata:type_name -> manager.AssignManagersRequest.MetadataEntry
	0, // 1: manager.ManagerService.AssignManagersAndWait:input_type -> manager.AssignManagersRequest
	1, // 2: manager.ManagerService.AssignManagersAndWait:output_type -> manager.AssignManagersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_boss_manager_proto_init() }
func file_boss_manager_proto_init() {
	if File_boss_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_manager_proto_rawDesc), len(file_boss_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boss_manager_proto_goTypes,
		DependencyIndexes: file_boss_manager_proto_depIdxs,
		MessageInfos:      file_boss_manager_proto_msgTypes,
	}.Build()
	File_boss_manager_proto = out.File
	file_boss_manager_proto_goTypes = nil
	file_boss_manager_proto_depIdxs = nil
}
