// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: worker-manager.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Task update message for streaming
type TaskUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          map[string]string      `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUpdate) Reset() {
	*x = TaskUpdate{}
	mi := &file_worker_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdate) ProtoMessage() {}

func (x *TaskUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_worker_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUpdate.ProtoReflect.Descriptor instead.
func (*TaskUpdate) Descriptor() ([]byte, []int) {
	return file_worker_manager_proto_rawDescGZIP(), []int{0}
}

func (x *TaskUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskUpdate) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TaskUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TaskUpdate) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type WorkerRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRole) Reset() {
	*x = WorkerRole{}
	mi := &file_worker_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRole) ProtoMessage() {}

func (x *WorkerRole) ProtoReflect() protoreflect.Message {
	mi := &file_worker_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRole.ProtoReflect.Descriptor instead.
func (*WorkerRole) Descriptor() ([]byte, []int) {
	return file_worker_manager_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WorkerRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// WorkerResult — результат работы воркера
type WorkerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	TaskMd        string                 `protobuf:"bytes,3,opt,name=task_md,json=taskMd,proto3" json:"task_md,omitempty"`
	SolutionMd    string                 `protobuf:"bytes,4,opt,name=solution_md,json=solutionMd,proto3" json:"solution_md,omitempty"`
	Files         map[string]string      `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // path -> content
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Feedback      string                 `protobuf:"bytes,7,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Approved      bool                   `protobuf:"varint,8,opt,name=approved,proto3" json:"approved,omitempty"`
	Commands      []string               `protobuf:"bytes,9,rep,name=commands,proto3" json:"commands,omitempty"` // команды для выполнения в проекте
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerResult) Reset() {
	*x = WorkerResult{}
	mi := &file_worker_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerResult) ProtoMessage() {}

func (x *WorkerResult) ProtoReflect() protoreflect.Message {
	mi := &file_worker_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerResult.ProtoReflect.Descriptor instead.
func (*WorkerResult) Descriptor() ([]byte, []int) {
	return file_worker_manager_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerResult) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WorkerResult) GetTaskMd() string {
	if x != nil {
		return x.TaskMd
	}
	return ""
}

func (x *WorkerResult) GetSolutionMd() string {
	if x != nil {
		return x.SolutionMd
	}
	return ""
}

func (x *WorkerResult) GetFiles() map[string]string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *WorkerResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WorkerResult) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *WorkerResult) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *WorkerResult) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

type AssignWorkersRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TaskId              string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ManagerId           string                 `protobuf:"bytes,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	ManagerRole         string                 `protobuf:"bytes,3,opt,name=manager_role,json=managerRole,proto3" json:"manager_role,omitempty"`
	WorkerRoles         []*WorkerRole          `protobuf:"bytes,4,rep,name=worker_roles,json=workerRoles,proto3" json:"worker_roles,omitempty"`
	TaskMd              string                 `protobuf:"bytes,5,opt,name=task_md,json=taskMd,proto3" json:"task_md,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OtherWorkersResults []*WorkerResult        `protobuf:"bytes,7,rep,name=other_workers_results,json=otherWorkersResults,proto3" json:"other_workers_results,omitempty"` // результаты других воркеров
	ProjectPath         string                 `protobuf:"bytes,8,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`                           // путь к папке проекта для Git
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AssignWorkersRequest) Reset() {
	*x = AssignWorkersRequest{}
	mi := &file_worker_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignWorkersRequest) ProtoMessage() {}

func (x *AssignWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignWorkersRequest.ProtoReflect.Descriptor instead.
func (*AssignWorkersRequest) Descriptor() ([]byte, []int) {
	return file_worker_manager_proto_rawDescGZIP(), []int{3}
}

func (x *AssignWorkersRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignWorkersRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AssignWorkersRequest) GetManagerRole() string {
	if x != nil {
		return x.ManagerRole
	}
	return ""
}

func (x *AssignWorkersRequest) GetWorkerRoles() []*WorkerRole {
	if x != nil {
		return x.WorkerRoles
	}
	return nil
}

func (x *AssignWorkersRequest) GetTaskMd() string {
	if x != nil {
		return x.TaskMd
	}
	return ""
}

func (x *AssignWorkersRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AssignWorkersRequest) GetOtherWorkersResults() []*WorkerResult {
	if x != nil {
		return x.OtherWorkersResults
	}
	return nil
}

func (x *AssignWorkersRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

type AssignWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	WorkerResults []*WorkerResult        `protobuf:"bytes,3,rep,name=worker_results,json=workerResults,proto3" json:"worker_results,omitempty"` // результаты всех воркеров
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignWorkersResponse) Reset() {
	*x = AssignWorkersResponse{}
	mi := &file_worker_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignWorkersResponse) ProtoMessage() {}

func (x *AssignWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignWorkersResponse.ProtoReflect.Descriptor instead.
func (*AssignWorkersResponse) Descriptor() ([]byte, []int) {
	return file_worker_manager_proto_rawDescGZIP(), []int{4}
}

func (x *AssignWorkersResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignWorkersResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AssignWorkersResponse) GetWorkerResults() []*WorkerResult {
	if x != nil {
		return x.WorkerResults
	}
	return nil
}

// ReviewRequest — запрос на исправление от менеджера
type ReviewRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ManagerId          string                 `protobuf:"bytes,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	WorkerId           string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkerRole         string                 `protobuf:"bytes,4,opt,name=worker_role,json=workerRole,proto3" json:"worker_role,omitempty"`
	Feedback           string                 `protobuf:"bytes,5,opt,name=feedback,proto3" json:"feedback,omitempty"` // замечания менеджера
	OriginalSolutionMd string                 `protobuf:"bytes,6,opt,name=original_solution_md,json=originalSolutionMd,proto3" json:"original_solution_md,omitempty"`
	OriginalFiles      map[string]string      `protobuf:"bytes,7,rep,name=original_files,json=originalFiles,proto3" json:"original_files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata           map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReviewRequest) Reset() {
	*x = ReviewRequest{}
	mi := &file_worker_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRequest) ProtoMessage() {}

func (x *ReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRequest.ProtoReflect.Descriptor instead.
func (*ReviewRequest) Descriptor() ([]byte, []int) {
	return file_worker_manager_proto_rawDescGZIP(), []int{5}
}

func (x *ReviewRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReviewRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *ReviewRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReviewRequest) GetWorkerRole() string {
	if x != nil {
		return x.WorkerRole
	}
	return ""
}

func (x *ReviewRequest) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *ReviewRequest) GetOriginalSolutionMd() string {
	if x != nil {
		return x.OriginalSolutionMd
	}
	return ""
}

func (x *ReviewRequest) GetOriginalFiles() map[string]string {
	if x != nil {
		return x.OriginalFiles
	}
	return nil
}

func (x *ReviewRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // fixed, failed
	SolutionMd    string                 `protobuf:"bytes,4,opt,name=solution_md,json=solutionMd,proto3" json:"solution_md,omitempty"`
	Files         map[string]string      `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Feedback      string                 `protobuf:"bytes,6,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_worker_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_worker_manager_proto_rawDescGZIP(), []int{6}
}

func (x *ReviewResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReviewResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReviewResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReviewResponse) GetSolutionMd() string {
	if x != nil {
		return x.SolutionMd
	}
	return ""
}

func (x *ReviewResponse) GetFiles() map[string]string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ReviewResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

var File_worker_manager_proto protoreflect.FileDescriptor

const file_worker_manager_proto_rawDesc = "" +
	"\n" +
	"\x14worker-manager.proto\x12\x06worker\"\xfc\x01\n" +
	"\n" +
	"TaskUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x120\n" +
	"\x04data\x18\x06 \x03(\v2\x1c.worker.TaskUpdate.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\n" +
	"WorkerRole\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xd8\x02\n" +
	"\fWorkerResult\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x17\n" +
	"\atask_md\x18\x03 \x01(\tR\x06taskMd\x12\x1f\n" +
	"\vsolution_md\x18\x04 \x01(\tR\n" +
	"solutionMd\x125\n" +
	"\x05files\x18\x05 \x03(\v2\x1f.worker.WorkerResult.FilesEntryR\x05files\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x1a\n" +
	"\bfeedback\x18\a \x01(\tR\bfeedback\x12\x1a\n" +
	"\bapproved\x18\b \x01(\bR\bapproved\x12\x1a\n" +
	"\bcommands\x18\t \x03(\tR\bcommands\x1a8\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x03\n" +
	"\x14AssignWorkersRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\tR\tmanagerId\x12!\n" +
	"\fmanager_role\x18\x03 \x01(\tR\vmanagerRole\x125\n" +
	"\fworker_roles\x18\x04 \x03(\v2\x12.worker.WorkerRoleR\vworkerRoles\x12\x17\n" +
	"\atask_md\x18\x05 \x01(\tR\x06taskMd\x12F\n" +
	"\bmetadata\x18\x06 \x03(\v2*.worker.AssignWorkersRequest.MetadataEntryR\bmetadata\x12H\n" +
	"\x15other_workers_results\x18\a \x03(\v2\x14.worker.WorkerResultR\x13otherWorkersResults\x12!\n" +
	"\fproject_path\x18\b \x01(\tR\vprojectPath\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\x15AssignWorkersResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12;\n" +
	"\x0eworker_results\x18\x03 \x03(\v2\x14.worker.WorkerResultR\rworkerResults\"\xe4\x03\n" +
	"\rReviewRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\tR\tmanagerId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vworker_role\x18\x04 \x01(\tR\n" +
	"workerRole\x12\x1a\n" +
	"\bfeedback\x18\x05 \x01(\tR\bfeedback\x120\n" +
	"\x14original_solution_md\x18\x06 \x01(\tR\x12originalSolutionMd\x12O\n" +
	"\x0eoriginal_files\x18\a \x03(\v2(.worker.ReviewRequest.OriginalFilesEntryR\roriginalFiles\x12?\n" +
	"\bmetadata\x18\b \x03(\v2#.worker.ReviewRequest.MetadataEntryR\bmetadata\x1a@\n" +
	"\x12OriginalFilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x02\n" +
	"\x0eReviewResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vsolution_md\x18\x04 \x01(\tR\n" +
	"solutionMd\x127\n" +
	"\x05files\x18\x05 \x03(\v2!.worker.ReviewResponse.FilesEntryR\x05files\x12\x1a\n" +
	"\bfeedback\x18\x06 \x01(\tR\bfeedback\x1a8\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xf5\x01\n" +
	"\rWorkerService\x12P\n" +
	"\x1aAssignWorkersAndWaitStream\x12\x1c.worker.AssignWorkersRequest\x1a\x12.worker.TaskUpdate0\x01\x12S\n" +
	"\x14AssignWorkersAndWait\x12\x1c.worker.AssignWorkersRequest\x1a\x1d.worker.AssignWorkersResponse\x12=\n" +
	"\fReviewWorker\x12\x15.worker.ReviewRequest\x1a\x16.worker.ReviewResponseB'Z%worker/internal/fetcher/grpc/workerpbb\x06proto3"

var (
	file_worker_manager_proto_rawDescOnce sync.Once
	file_worker_manager_proto_rawDescData []byte
)

func file_worker_manager_proto_rawDescGZIP() []byte {
	file_worker_manager_proto_rawDescOnce.Do(func() {
		file_worker_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_manager_proto_rawDesc), len(file_worker_manager_proto_rawDesc)))
	})
	return file_worker_manager_proto_rawDescData
}

var file_worker_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_worker_manager_proto_goTypes = []any{
	(*TaskUpdate)(nil),            // 0: worker.TaskUpdate
	(*WorkerRole)(nil),            // 1: worker.WorkerRole
	(*WorkerResult)(nil),          // 2: worker.WorkerResult
	(*AssignWorkersRequest)(nil),  // 3: worker.AssignWorkersRequest
	(*AssignWorkersResponse)(nil), // 4: worker.AssignWorkersResponse
	(*ReviewRequest)(nil),         // 5: worker.ReviewRequest
	(*ReviewResponse)(nil),        // 6: worker.ReviewResponse
	nil,                           // 7: worker.TaskUpdate.DataEntry
	nil,                           // 8: worker.WorkerResult.FilesEntry
	nil,                           // 9: worker.AssignWorkersRequest.MetadataEntry
	nil,                           // 10: worker.ReviewRequest.OriginalFilesEntry
	nil,                           // 11: worker.ReviewRequest.MetadataEntry
	nil,                           // 12: worker.ReviewResponse.FilesEntry
}
var file_worker_manager_proto_depIdxs = []int32{
	7,  // 0: worker.TaskUpdate.data:type_name -> worker.TaskUpdate.DataEntry
	8,  // 1: worker.WorkerResult.files:type_name -> worker.WorkerResult.FilesEntry
	1,  // 2: worker.AssignWorkersRequest.worker_roles:type_name -> worker.WorkerRole
	9,  // 3: worker.AssignWorkersRequest.metadata:type_name -> worker.AssignWorkersRequest.MetadataEntry
	2,  // 4: worker.AssignWorkersRequest.other_workers_results:type_name -> worker.WorkerResult
	2,  // 5: worker.AssignWorkersResponse.worker_results:type_name -> worker.WorkerResult
	10, // 6: worker.ReviewRequest.original_files:type_name -> worker.ReviewRequest.OriginalFilesEntry
	11, // 7: worker.ReviewRequest.metadata:type_name -> worker.ReviewRequest.MetadataEntry
	12, // 8: worker.ReviewResponse.files:type_name -> worker.ReviewResponse.FilesEntry
	3,  // 9: worker.WorkerService.AssignWorkersAndWaitStream:input_type -> worker.AssignWorkersRequest
	3,  // 10: worker.WorkerService.AssignWorkersAndWait:input_type -> worker.AssignWorkersRequest
	5,  // 11: worker.WorkerService.ReviewWorker:input_type -> worker.ReviewRequest
	0,  // 12: worker.WorkerService.AssignWorkersAndWaitStream:output_type -> worker.TaskUpdate
	4,  // 13: worker.WorkerService.AssignWorkersAndWait:output_type -> worker.AssignWorkersResponse
	6,  // 14: worker.WorkerService.ReviewWorker:output_type -> worker.ReviewResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_worker_manager_proto_init() }
func file_worker_manager_proto_init() {
	if File_worker_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_manager_proto_rawDesc), len(file_worker_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_manager_proto_goTypes,
		DependencyIndexes: file_worker_manager_proto_depIdxs,
		MessageInfos:      file_worker_manager_proto_msgTypes,
	}.Build()
	File_worker_manager_proto = out.File
	file_worker_manager_proto_goTypes = nil
	file_worker_manager_proto_depIdxs = nil
}
