// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: manager-worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Роль воркера
type WorkerRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRole) Reset() {
	*x = WorkerRole{}
	mi := &file_manager_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRole) ProtoMessage() {}

func (x *WorkerRole) ProtoReflect() protoreflect.Message {
	mi := &file_manager_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRole.ProtoReflect.Descriptor instead.
func (*WorkerRole) Descriptor() ([]byte, []int) {
	return file_manager_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WorkerRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Информация о воркере
type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	SolutionMd    string                 `protobuf:"bytes,4,opt,name=solution_md,json=solutionMd,proto3" json:"solution_md,omitempty"`
	Files         []string               `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_manager_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_manager_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_manager_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkerInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WorkerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerInfo) GetSolutionMd() string {
	if x != nil {
		return x.SolutionMd
	}
	return ""
}

func (x *WorkerInfo) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

// Результат работы воркера
type WorkerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ManagerId     string                 `protobuf:"bytes,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Files         map[string][]byte      `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SolutionMd    string                 `protobuf:"bytes,5,opt,name=solution_md,json=solutionMd,proto3" json:"solution_md,omitempty"`
	Logs          string                 `protobuf:"bytes,6,opt,name=logs,proto3" json:"logs,omitempty"`
	Success       bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerResult) Reset() {
	*x = WorkerResult{}
	mi := &file_manager_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerResult) ProtoMessage() {}

func (x *WorkerResult) ProtoReflect() protoreflect.Message {
	mi := &file_manager_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerResult.ProtoReflect.Descriptor instead.
func (*WorkerResult) Descriptor() ([]byte, []int) {
	return file_manager_worker_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WorkerResult) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *WorkerResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerResult) GetFiles() map[string][]byte {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *WorkerResult) GetSolutionMd() string {
	if x != nil {
		return x.SolutionMd
	}
	return ""
}

func (x *WorkerResult) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

func (x *WorkerResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос от manager к worker
type AssignWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ManagerId     string                 `protobuf:"bytes,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	ManagerRole   string                 `protobuf:"bytes,3,opt,name=manager_role,json=managerRole,proto3" json:"manager_role,omitempty"`
	WorkerRoles   []*WorkerRole          `protobuf:"bytes,4,rep,name=worker_roles,json=workerRoles,proto3" json:"worker_roles,omitempty"`
	TaskMd        string                 `protobuf:"bytes,5,opt,name=task_md,json=taskMd,proto3" json:"task_md,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignWorkersRequest) Reset() {
	*x = AssignWorkersRequest{}
	mi := &file_manager_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignWorkersRequest) ProtoMessage() {}

func (x *AssignWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignWorkersRequest.ProtoReflect.Descriptor instead.
func (*AssignWorkersRequest) Descriptor() ([]byte, []int) {
	return file_manager_worker_proto_rawDescGZIP(), []int{3}
}

func (x *AssignWorkersRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignWorkersRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AssignWorkersRequest) GetManagerRole() string {
	if x != nil {
		return x.ManagerRole
	}
	return ""
}

func (x *AssignWorkersRequest) GetWorkerRoles() []*WorkerRole {
	if x != nil {
		return x.WorkerRoles
	}
	return nil
}

func (x *AssignWorkersRequest) GetTaskMd() string {
	if x != nil {
		return x.TaskMd
	}
	return ""
}

// Ответ worker
type AssignWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Workers       []*WorkerInfo          `protobuf:"bytes,3,rep,name=workers,proto3" json:"workers,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignWorkersResponse) Reset() {
	*x = AssignWorkersResponse{}
	mi := &file_manager_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignWorkersResponse) ProtoMessage() {}

func (x *AssignWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignWorkersResponse.ProtoReflect.Descriptor instead.
func (*AssignWorkersResponse) Descriptor() ([]byte, []int) {
	return file_manager_worker_proto_rawDescGZIP(), []int{4}
}

func (x *AssignWorkersResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignWorkersResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AssignWorkersResponse) GetWorkers() []*WorkerInfo {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *AssignWorkersResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Запрос на проверку результата
type ReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ManagerId     string                 `protobuf:"bytes,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	Result        *WorkerResult          `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewRequest) Reset() {
	*x = ReviewRequest{}
	mi := &file_manager_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRequest) ProtoMessage() {}

func (x *ReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRequest.ProtoReflect.Descriptor instead.
func (*ReviewRequest) Descriptor() ([]byte, []int) {
	return file_manager_worker_proto_rawDescGZIP(), []int{5}
}

func (x *ReviewRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReviewRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *ReviewRequest) GetResult() *WorkerResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	Feedback      string                 `protobuf:"bytes,2,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_manager_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_manager_worker_proto_rawDescGZIP(), []int{6}
}

func (x *ReviewResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ReviewResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

var File_manager_worker_proto protoreflect.FileDescriptor

const file_manager_worker_proto_rawDesc = "" +
	"\n" +
	"\x14manager-worker.proto\x12\x06worker\"B\n" +
	"\n" +
	"WorkerRole\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x7f\n" +
	"\n" +
	"WorkerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vsolution_md\x18\x04 \x01(\tR\n" +
	"solutionMd\x12\x14\n" +
	"\x05files\x18\x05 \x03(\tR\x05files\"\xa3\x02\n" +
	"\fWorkerResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\tR\tmanagerId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x125\n" +
	"\x05files\x18\x04 \x03(\v2\x1f.worker.WorkerResult.FilesEntryR\x05files\x12\x1f\n" +
	"\vsolution_md\x18\x05 \x01(\tR\n" +
	"solutionMd\x12\x12\n" +
	"\x04logs\x18\x06 \x01(\tR\x04logs\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x1a8\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xc1\x01\n" +
	"\x14AssignWorkersRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\tR\tmanagerId\x12!\n" +
	"\fmanager_role\x18\x03 \x01(\tR\vmanagerRole\x125\n" +
	"\fworker_roles\x18\x04 \x03(\v2\x12.worker.WorkerRoleR\vworkerRoles\x12\x17\n" +
	"\atask_md\x18\x05 \x01(\tR\x06taskMd\"\x9b\x01\n" +
	"\x15AssignWorkersResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12,\n" +
	"\aworkers\x18\x03 \x03(\v2\x12.worker.WorkerInfoR\aworkers\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"u\n" +
	"\rReviewRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\tR\tmanagerId\x12,\n" +
	"\x06result\x18\x03 \x01(\v2\x14.worker.WorkerResultR\x06result\"H\n" +
	"\x0eReviewResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x1a\n" +
	"\bfeedback\x18\x02 \x01(\tR\bfeedback2\x9b\x01\n" +
	"\rWorkerService\x12L\n" +
	"\rAssignWorkers\x12\x1c.worker.AssignWorkersRequest\x1a\x1d.worker.AssignWorkersResponse\x12<\n" +
	"\fSubmitResult\x12\x14.worker.WorkerResult\x1a\x16.worker.ReviewResponseB'Z%worker/internal/fetcher/grpc/workerpbb\x06proto3"

var (
	file_manager_worker_proto_rawDescOnce sync.Once
	file_manager_worker_proto_rawDescData []byte
)

func file_manager_worker_proto_rawDescGZIP() []byte {
	file_manager_worker_proto_rawDescOnce.Do(func() {
		file_manager_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_worker_proto_rawDesc), len(file_manager_worker_proto_rawDesc)))
	})
	return file_manager_worker_proto_rawDescData
}

var file_manager_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_manager_worker_proto_goTypes = []any{
	(*WorkerRole)(nil),            // 0: worker.WorkerRole
	(*WorkerInfo)(nil),            // 1: worker.WorkerInfo
	(*WorkerResult)(nil),          // 2: worker.WorkerResult
	(*AssignWorkersRequest)(nil),  // 3: worker.AssignWorkersRequest
	(*AssignWorkersResponse)(nil), // 4: worker.AssignWorkersResponse
	(*ReviewRequest)(nil),         // 5: worker.ReviewRequest
	(*ReviewResponse)(nil),        // 6: worker.ReviewResponse
	nil,                           // 7: worker.WorkerResult.FilesEntry
}
var file_manager_worker_proto_depIdxs = []int32{
	7, // 0: worker.WorkerResult.files:type_name -> worker.WorkerResult.FilesEntry
	0, // 1: worker.AssignWorkersRequest.worker_roles:type_name -> worker.WorkerRole
	1, // 2: worker.AssignWorkersResponse.workers:type_name -> worker.WorkerInfo
	2, // 3: worker.ReviewRequest.result:type_name -> worker.WorkerResult
	3, // 4: worker.WorkerService.AssignWorkers:input_type -> worker.AssignWorkersRequest
	2, // 5: worker.WorkerService.SubmitResult:input_type -> worker.WorkerResult
	4, // 6: worker.WorkerService.AssignWorkers:output_type -> worker.AssignWorkersResponse
	6, // 7: worker.WorkerService.SubmitResult:output_type -> worker.ReviewResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_manager_worker_proto_init() }
func file_manager_worker_proto_init() {
	if File_manager_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_worker_proto_rawDesc), len(file_manager_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_worker_proto_goTypes,
		DependencyIndexes: file_manager_worker_proto_depIdxs,
		MessageInfos:      file_manager_worker_proto_msgTypes,
	}.Build()
	File_manager_worker_proto = out.File
	file_manager_worker_proto_goTypes = nil
	file_manager_worker_proto_depIdxs = nil
}
