// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: boss.proto

package bosspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BossService_CreateTaskStream_FullMethodName = "/boss.BossService/CreateTaskStream"
	BossService_CreateTask_FullMethodName       = "/boss.BossService/CreateTask"
	BossService_GetTaskStatus_FullMethodName    = "/boss.BossService/GetTaskStatus"
)

// BossServiceClient is the client API for BossService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BossServiceClient interface {
	// Streaming version - отправляет обновления по мере выполнения
	CreateTaskStream(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskUpdate], error)
	// Legacy unary version (для совместимости)
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*BossDecision, error)
	GetTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error)
}

type bossServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBossServiceClient(cc grpc.ClientConnInterface) BossServiceClient {
	return &bossServiceClient{cc}
}

func (c *bossServiceClient) CreateTaskStream(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BossService_ServiceDesc.Streams[0], BossService_CreateTaskStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateTaskRequest, TaskUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BossService_CreateTaskStreamClient = grpc.ServerStreamingClient[TaskUpdate]

func (c *bossServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*BossDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BossDecision)
	err := c.cc.Invoke(ctx, BossService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bossServiceClient) GetTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatusResponse)
	err := c.cc.Invoke(ctx, BossService_GetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BossServiceServer is the server API for BossService service.
// All implementations must embed UnimplementedBossServiceServer
// for forward compatibility.
type BossServiceServer interface {
	// Streaming version - отправляет обновления по мере выполнения
	CreateTaskStream(*CreateTaskRequest, grpc.ServerStreamingServer[TaskUpdate]) error
	// Legacy unary version (для совместимости)
	CreateTask(context.Context, *CreateTaskRequest) (*BossDecision, error)
	GetTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error)
	mustEmbedUnimplementedBossServiceServer()
}

// UnimplementedBossServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBossServiceServer struct{}

func (UnimplementedBossServiceServer) CreateTaskStream(*CreateTaskRequest, grpc.ServerStreamingServer[TaskUpdate]) error {
	return status.Error(codes.Unimplemented, "method CreateTaskStream not implemented")
}
func (UnimplementedBossServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*BossDecision, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedBossServiceServer) GetTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedBossServiceServer) mustEmbedUnimplementedBossServiceServer() {}
func (UnimplementedBossServiceServer) testEmbeddedByValue()                     {}

// UnsafeBossServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BossServiceServer will
// result in compilation errors.
type UnsafeBossServiceServer interface {
	mustEmbedUnimplementedBossServiceServer()
}

func RegisterBossServiceServer(s grpc.ServiceRegistrar, srv BossServiceServer) {
	// If the following call panics, it indicates UnimplementedBossServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BossService_ServiceDesc, srv)
}

func _BossService_CreateTaskStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BossServiceServer).CreateTaskStream(m, &grpc.GenericServerStream[CreateTaskRequest, TaskUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BossService_CreateTaskStreamServer = grpc.ServerStreamingServer[TaskUpdate]

func _BossService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BossServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BossService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BossServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BossService_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BossServiceServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BossService_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BossServiceServer).GetTaskStatus(ctx, req.(*TaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BossService_ServiceDesc is the grpc.ServiceDesc for BossService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BossService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "boss.BossService",
	HandlerType: (*BossServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _BossService_CreateTask_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _BossService_GetTaskStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateTaskStream",
			Handler:       _BossService_CreateTaskStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "boss.proto",
}
