const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? '';

export const ROUTES = {
  HOME: '/',
  WORKSPACE: '/app',
  LOGIN: '/login',
  LOGIN_GOOGLE: '/login/google',
  LOGIN_GITHUB: '/login/github',
  LOGIN_LEFINE: '/login/lefine',
  DASHBOARD: '/dashboard',
  DASHBOARD_ENVIRONMENTS: '/dashboard/environments',
  DASHBOARD_FLOWS: '/dashboard/flows',
  DASHBOARD_MODELS: '/dashboard/models',
  DASHBOARD_FILES: '/dashboard/files',
  DASHBOARD_SECURITY: '/dashboard/security',
  DASHBOARD_METRICS: '/dashboard/metrics',
  DASHBOARD_EVALUATIONS: '/dashboard/evaluations',
  DASHBOARD_DEPLOYMENTS: '/dashboard/deployments',
  DASHBOARD_MCP: '/dashboard/mcp',
  DASHBOARD_RUNS: '/dashboard/runs',
  DASHBOARD_HITL: '/dashboard/hitl',
  DASHBOARD_TRIGGERS: '/dashboard/triggers',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  PROFILE_SETTINGS: '/profile/settings',
  PROFILE_API: '/profile/api',
} as const;

export const API = {
  BASE: API_BASE,
  LOGIN: `${API_BASE}/login`,
  REGISTER: `${API_BASE}/register`,
  ME: `${API_BASE}/me`,
  KEYS: `${API_BASE}/api/keys`,
  ENVIRONMENTS: `${API_BASE}/api/environments`,
  CLIS: `${API_BASE}/api/cli`,
  CLI_SEARCH: `${API_BASE}/api/cli/search`,
  PROVIDERS: `${API_BASE}/api/providers`,
  PROVIDER_SEARCH: `${API_BASE}/api/providers/search`,
  SKILLS_SEARCH: `${API_BASE}/skills/search`,
  CATALOG_SEARCH: `${API_BASE}/api/catalog/search`,
  METRICS_REQUESTS: `${API_BASE}/api/metrics/requests`,
  MCP_SERVERS: `${API_BASE}/v1/mcp/servers`,
  MCP_CATALOG: `${API_BASE}/v1/mcp/catalog`,
  WORKFLOW_RUNS: (workflowId: string) => `${API_BASE}/v1/workflows/${workflowId}/runs`,
  WORKFLOW_RUN: (workflowId: string, runId: string) => `${API_BASE}/v1/workflows/${workflowId}/runs/${runId}`,
  HITL_RUNS: `${API_BASE}/v1/hitl/runs`,
  HITL_RUN: (workflowId: string, runId: string) => `${API_BASE}/v1/hitl/runs/${workflowId}/${runId}`,
  HITL_RUN_ACTIONS: (workflowId: string, runId: string) => `${API_BASE}/v1/hitl/runs/${workflowId}/${runId}/actions`,
  TRIGGERS: `${API_BASE}/v1/triggers`,
} as const;
