// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: boss-manager.proto

package managerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Роль воркера (определяется локально)
type WorkerRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRole) Reset() {
	*x = WorkerRole{}
	mi := &file_boss_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRole) ProtoMessage() {}

func (x *WorkerRole) ProtoReflect() protoreflect.Message {
	mi := &file_boss_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRole.ProtoReflect.Descriptor instead.
func (*WorkerRole) Descriptor() ([]byte, []int) {
	return file_boss_manager_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WorkerRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Информация о менеджере
type ManagerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	WorkerRoles   []*WorkerRole          `protobuf:"bytes,4,rep,name=worker_roles,json=workerRoles,proto3" json:"worker_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerInfo) Reset() {
	*x = ManagerInfo{}
	mi := &file_boss_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerInfo) ProtoMessage() {}

func (x *ManagerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_boss_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerInfo.ProtoReflect.Descriptor instead.
func (*ManagerInfo) Descriptor() ([]byte, []int) {
	return file_boss_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManagerInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ManagerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ManagerInfo) GetWorkerRoles() []*WorkerRole {
	if x != nil {
		return x.WorkerRoles
	}
	return nil
}

// Запрос от boss к manager
type AssignManagersRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskId               string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TechnicalDescription string                 `protobuf:"bytes,2,opt,name=technical_description,json=technicalDescription,proto3" json:"technical_description,omitempty"`
	TechStack            []string               `protobuf:"bytes,3,rep,name=tech_stack,json=techStack,proto3" json:"tech_stack,omitempty"`
	ManagerRoles         []*ManagerRole         `protobuf:"bytes,4,rep,name=manager_roles,json=managerRoles,proto3" json:"manager_roles,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AssignManagersRequest) Reset() {
	*x = AssignManagersRequest{}
	mi := &file_boss_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignManagersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignManagersRequest) ProtoMessage() {}

func (x *AssignManagersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignManagersRequest.ProtoReflect.Descriptor instead.
func (*AssignManagersRequest) Descriptor() ([]byte, []int) {
	return file_boss_manager_proto_rawDescGZIP(), []int{2}
}

func (x *AssignManagersRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignManagersRequest) GetTechnicalDescription() string {
	if x != nil {
		return x.TechnicalDescription
	}
	return ""
}

func (x *AssignManagersRequest) GetTechStack() []string {
	if x != nil {
		return x.TechStack
	}
	return nil
}

func (x *AssignManagersRequest) GetManagerRoles() []*ManagerRole {
	if x != nil {
		return x.ManagerRoles
	}
	return nil
}

// Роль менеджера (копия из boss.proto для независимости)
type ManagerRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerRole) Reset() {
	*x = ManagerRole{}
	mi := &file_boss_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerRole) ProtoMessage() {}

func (x *ManagerRole) ProtoReflect() protoreflect.Message {
	mi := &file_boss_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerRole.ProtoReflect.Descriptor instead.
func (*ManagerRole) Descriptor() ([]byte, []int) {
	return file_boss_manager_proto_rawDescGZIP(), []int{3}
}

func (x *ManagerRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ManagerRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ManagerRole) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// Ответ manager
type AssignManagersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Managers      []*ManagerInfo         `protobuf:"bytes,3,rep,name=managers,proto3" json:"managers,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignManagersResponse) Reset() {
	*x = AssignManagersResponse{}
	mi := &file_boss_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignManagersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignManagersResponse) ProtoMessage() {}

func (x *AssignManagersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boss_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignManagersResponse.ProtoReflect.Descriptor instead.
func (*AssignManagersResponse) Descriptor() ([]byte, []int) {
	return file_boss_manager_proto_rawDescGZIP(), []int{4}
}

func (x *AssignManagersResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignManagersResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AssignManagersResponse) GetManagers() []*ManagerInfo {
	if x != nil {
		return x.Managers
	}
	return nil
}

func (x *AssignManagersResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Запрос на получение задачи для менеджера
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManagerId     string                 `protobuf:"bytes,1,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_boss_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_boss_manager_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

type GetTaskResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskId               string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TechnicalDescription string                 `protobuf:"bytes,2,opt,name=technical_description,json=technicalDescription,proto3" json:"technical_description,omitempty"`
	TechStack            []string               `protobuf:"bytes,3,rep,name=tech_stack,json=techStack,proto3" json:"tech_stack,omitempty"`
	ManagerRole          string                 `protobuf:"bytes,4,opt,name=manager_role,json=managerRole,proto3" json:"manager_role,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_boss_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boss_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_boss_manager_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskResponse) GetTechnicalDescription() string {
	if x != nil {
		return x.TechnicalDescription
	}
	return ""
}

func (x *GetTaskResponse) GetTechStack() []string {
	if x != nil {
		return x.TechStack
	}
	return nil
}

func (x *GetTaskResponse) GetManagerRole() string {
	if x != nil {
		return x.ManagerRole
	}
	return ""
}

var File_boss_manager_proto protoreflect.FileDescriptor

const file_boss_manager_proto_rawDesc = "" +
	"\n" +
	"\x12boss-manager.proto\x12\amanager\"B\n" +
	"\n" +
	"WorkerRole\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x81\x01\n" +
	"\vManagerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x126\n" +
	"\fworker_roles\x18\x04 \x03(\v2\x13.manager.WorkerRoleR\vworkerRoles\"\xbf\x01\n" +
	"\x15AssignManagersRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x123\n" +
	"\x15technical_description\x18\x02 \x01(\tR\x14technicalDescription\x12\x1d\n" +
	"\n" +
	"tech_stack\x18\x03 \x03(\tR\ttechStack\x129\n" +
	"\rmanager_roles\x18\x04 \x03(\v2\x14.manager.ManagerRoleR\fmanagerRoles\"_\n" +
	"\vManagerRole\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\"\xa0\x01\n" +
	"\x16AssignManagersResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x120\n" +
	"\bmanagers\x18\x03 \x03(\v2\x14.manager.ManagerInfoR\bmanagers\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"/\n" +
	"\x0eGetTaskRequest\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x01 \x01(\tR\tmanagerId\"\xa1\x01\n" +
	"\x0fGetTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x123\n" +
	"\x15technical_description\x18\x02 \x01(\tR\x14technicalDescription\x12\x1d\n" +
	"\n" +
	"tech_stack\x18\x03 \x03(\tR\ttechStack\x12!\n" +
	"\fmanager_role\x18\x04 \x01(\tR\vmanagerRole2\xa1\x01\n" +
	"\x0eManagerService\x12Q\n" +
	"\x0eAssignManagers\x12\x1e.manager.AssignManagersRequest\x1a\x1f.manager.AssignManagersResponse\x12<\n" +
	"\aGetTask\x12\x17.manager.GetTaskRequest\x1a\x18.manager.GetTaskResponseB)Z'manager/internal/fetcher/grpc/managerpbb\x06proto3"

var (
	file_boss_manager_proto_rawDescOnce sync.Once
	file_boss_manager_proto_rawDescData []byte
)

func file_boss_manager_proto_rawDescGZIP() []byte {
	file_boss_manager_proto_rawDescOnce.Do(func() {
		file_boss_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_manager_proto_rawDesc), len(file_boss_manager_proto_rawDesc)))
	})
	return file_boss_manager_proto_rawDescData
}

var file_boss_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_boss_manager_proto_goTypes = []any{
	(*WorkerRole)(nil),             // 0: manager.WorkerRole
	(*ManagerInfo)(nil),            // 1: manager.ManagerInfo
	(*AssignManagersRequest)(nil),  // 2: manager.AssignManagersRequest
	(*ManagerRole)(nil),            // 3: manager.ManagerRole
	(*AssignManagersResponse)(nil), // 4: manager.AssignManagersResponse
	(*GetTaskRequest)(nil),         // 5: manager.GetTaskRequest
	(*GetTaskResponse)(nil),        // 6: manager.GetTaskResponse
}
var file_boss_manager_proto_depIdxs = []int32{
	0, // 0: manager.ManagerInfo.worker_roles:type_name -> manager.WorkerRole
	3, // 1: manager.AssignManagersRequest.manager_roles:type_name -> manager.ManagerRole
	1, // 2: manager.AssignManagersResponse.managers:type_name -> manager.ManagerInfo
	2, // 3: manager.ManagerService.AssignManagers:input_type -> manager.AssignManagersRequest
	5, // 4: manager.ManagerService.GetTask:input_type -> manager.GetTaskRequest
	4, // 5: manager.ManagerService.AssignManagers:output_type -> manager.AssignManagersResponse
	6, // 6: manager.ManagerService.GetTask:output_type -> manager.GetTaskResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_boss_manager_proto_init() }
func file_boss_manager_proto_init() {
	if File_boss_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_manager_proto_rawDesc), len(file_boss_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boss_manager_proto_goTypes,
		DependencyIndexes: file_boss_manager_proto_depIdxs,
		MessageInfos:      file_boss_manager_proto_msgTypes,
	}.Build()
	File_boss_manager_proto = out.File
	file_boss_manager_proto_goTypes = nil
	file_boss_manager_proto_depIdxs = nil
}
