// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: boss.proto

package bosspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Task update message for streaming
type TaskUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          map[string]string      `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUpdate) Reset() {
	*x = TaskUpdate{}
	mi := &file_boss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdate) ProtoMessage() {}

func (x *TaskUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_boss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUpdate.ProtoReflect.Descriptor instead.
func (*TaskUpdate) Descriptor() ([]byte, []int) {
	return file_boss_proto_rawDescGZIP(), []int{0}
}

func (x *TaskUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskUpdate) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TaskUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TaskUpdate) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request from apigateway to boss
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tokens        []string               `protobuf:"bytes,5,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // model, modelUrl
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_boss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_boss_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTaskRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *CreateTaskRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Manager role
type ManagerRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerRole) Reset() {
	*x = ManagerRole{}
	mi := &file_boss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerRole) ProtoMessage() {}

func (x *ManagerRole) ProtoReflect() protoreflect.Message {
	mi := &file_boss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerRole.ProtoReflect.Descriptor instead.
func (*ManagerRole) Descriptor() ([]byte, []int) {
	return file_boss_proto_rawDescGZIP(), []int{2}
}

func (x *ManagerRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ManagerRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ManagerRole) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// Boss decision with ZIP solution
type BossDecision struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskId               string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status               string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // done, error
	ManagersCount        int32                  `protobuf:"varint,3,opt,name=managers_count,json=managersCount,proto3" json:"managers_count,omitempty"`
	ManagerRoles         []*ManagerRole         `protobuf:"bytes,4,rep,name=manager_roles,json=managerRoles,proto3" json:"manager_roles,omitempty"`
	TechnicalDescription string                 `protobuf:"bytes,5,opt,name=technical_description,json=technicalDescription,proto3" json:"technical_description,omitempty"`
	TechStack            []string               `protobuf:"bytes,6,rep,name=tech_stack,json=techStack,proto3" json:"tech_stack,omitempty"`
	ArchitectureNotes    string                 `protobuf:"bytes,7,opt,name=architecture_notes,json=architectureNotes,proto3" json:"architecture_notes,omitempty"`
	Solution             []byte                 `protobuf:"bytes,8,opt,name=solution,proto3" json:"solution,omitempty"` // ZIP archive
	ErrorMessage         string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BossDecision) Reset() {
	*x = BossDecision{}
	mi := &file_boss_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BossDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossDecision) ProtoMessage() {}

func (x *BossDecision) ProtoReflect() protoreflect.Message {
	mi := &file_boss_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossDecision.ProtoReflect.Descriptor instead.
func (*BossDecision) Descriptor() ([]byte, []int) {
	return file_boss_proto_rawDescGZIP(), []int{3}
}

func (x *BossDecision) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *BossDecision) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BossDecision) GetManagersCount() int32 {
	if x != nil {
		return x.ManagersCount
	}
	return 0
}

func (x *BossDecision) GetManagerRoles() []*ManagerRole {
	if x != nil {
		return x.ManagerRoles
	}
	return nil
}

func (x *BossDecision) GetTechnicalDescription() string {
	if x != nil {
		return x.TechnicalDescription
	}
	return ""
}

func (x *BossDecision) GetTechStack() []string {
	if x != nil {
		return x.TechStack
	}
	return nil
}

func (x *BossDecision) GetArchitectureNotes() string {
	if x != nil {
		return x.ArchitectureNotes
	}
	return ""
}

func (x *BossDecision) GetSolution() []byte {
	if x != nil {
		return x.Solution
	}
	return nil
}

func (x *BossDecision) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Task status request
type TaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusRequest) Reset() {
	*x = TaskStatusRequest{}
	mi := &file_boss_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusRequest) ProtoMessage() {}

func (x *TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boss_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_boss_proto_rawDescGZIP(), []int{4}
}

func (x *TaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Progress      string                 `protobuf:"bytes,3,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_boss_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boss_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_boss_proto_rawDescGZIP(), []int{5}
}

func (x *TaskStatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskStatusResponse) GetProgress() string {
	if x != nil {
		return x.Progress
	}
	return ""
}

var File_boss_proto protoreflect.FileDescriptor

const file_boss_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"boss.proto\x12\x04boss\"\xfa\x01\n" +
	"\n" +
	"TaskUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12.\n" +
	"\x04data\x18\x06 \x03(\v2\x1a.boss.TaskUpdate.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x02\n" +
	"\x11CreateTaskRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06tokens\x18\x05 \x03(\tR\x06tokens\x125\n" +
	"\x04meta\x18\x06 \x03(\v2!.boss.CreateTaskRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\vManagerRole\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\"\xe2\x02\n" +
	"\fBossDecision\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0emanagers_count\x18\x03 \x01(\x05R\rmanagersCount\x126\n" +
	"\rmanager_roles\x18\x04 \x03(\v2\x11.boss.ManagerRoleR\fmanagerRoles\x123\n" +
	"\x15technical_description\x18\x05 \x01(\tR\x14technicalDescription\x12\x1d\n" +
	"\n" +
	"tech_stack\x18\x06 \x03(\tR\ttechStack\x12-\n" +
	"\x12architecture_notes\x18\a \x01(\tR\x11architectureNotes\x12\x1a\n" +
	"\bsolution\x18\b \x01(\fR\bsolution\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\",\n" +
	"\x11TaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"a\n" +
	"\x12TaskStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\tR\bprogress2\xcd\x01\n" +
	"\vBossService\x12?\n" +
	"\x10CreateTaskStream\x12\x17.boss.CreateTaskRequest\x1a\x10.boss.TaskUpdate0\x01\x129\n" +
	"\n" +
	"CreateTask\x12\x17.boss.CreateTaskRequest\x1a\x12.boss.BossDecision\x12B\n" +
	"\rGetTaskStatus\x12\x17.boss.TaskStatusRequest\x1a\x18.boss.TaskStatusResponseB*Z(crewai/internal/fetcher/grpc/boss/bosspbb\x06proto3"

var (
	file_boss_proto_rawDescOnce sync.Once
	file_boss_proto_rawDescData []byte
)

func file_boss_proto_rawDescGZIP() []byte {
	file_boss_proto_rawDescOnce.Do(func() {
		file_boss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boss_proto_rawDesc), len(file_boss_proto_rawDesc)))
	})
	return file_boss_proto_rawDescData
}

var file_boss_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_boss_proto_goTypes = []any{
	(*TaskUpdate)(nil),         // 0: boss.TaskUpdate
	(*CreateTaskRequest)(nil),  // 1: boss.CreateTaskRequest
	(*ManagerRole)(nil),        // 2: boss.ManagerRole
	(*BossDecision)(nil),       // 3: boss.BossDecision
	(*TaskStatusRequest)(nil),  // 4: boss.TaskStatusRequest
	(*TaskStatusResponse)(nil), // 5: boss.TaskStatusResponse
	nil,                        // 6: boss.TaskUpdate.DataEntry
	nil,                        // 7: boss.CreateTaskRequest.MetaEntry
}
var file_boss_proto_depIdxs = []int32{
	6, // 0: boss.TaskUpdate.data:type_name -> boss.TaskUpdate.DataEntry
	7, // 1: boss.CreateTaskRequest.meta:type_name -> boss.CreateTaskRequest.MetaEntry
	2, // 2: boss.BossDecision.manager_roles:type_name -> boss.ManagerRole
	1, // 3: boss.BossService.CreateTaskStream:input_type -> boss.CreateTaskRequest
	1, // 4: boss.BossService.CreateTask:input_type -> boss.CreateTaskRequest
	4, // 5: boss.BossService.GetTaskStatus:input_type -> boss.TaskStatusRequest
	0, // 6: boss.BossService.CreateTaskStream:output_type -> boss.TaskUpdate
	3, // 7: boss.BossService.CreateTask:output_type -> boss.BossDecision
	5, // 8: boss.BossService.GetTaskStatus:output_type -> boss.TaskStatusResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_boss_proto_init() }
func file_boss_proto_init() {
	if File_boss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boss_proto_rawDesc), len(file_boss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boss_proto_goTypes,
		DependencyIndexes: file_boss_proto_depIdxs,
		MessageInfos:      file_boss_proto_msgTypes,
	}.Build()
	File_boss_proto = out.File
	file_boss_proto_goTypes = nil
	file_boss_proto_depIdxs = nil
}
