// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: agents.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerateRequest is the request to generate content
type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                                                                       // claude, gemini, openai, deepseek, grok
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`                                                                             // specific model name
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`                                                                           // the prompt
	Tokens        map[string]string      `protobuf:"bytes,4,rep,name=tokens,proto3" json:"tokens,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // auth tokens
	MaxTokens     int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`                                                   // response max tokens
	Temperature   float32                `protobuf:"fixed32,6,opt,name=temperature,proto3" json:"temperature,omitempty"`                                                               // creativity parameter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_agents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GenerateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetTokens() map[string]string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *GenerateRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GenerateRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

// GenerateResponse is the response from generation
type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_agents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GenerateResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GenerateResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *GenerateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GenerateResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

var File_agents_proto protoreflect.FileDescriptor

const file_agents_proto_rawDesc = "" +
	"\n" +
	"\fagents.proto\x12\bagentspb\"\x96\x02\n" +
	"\x0fGenerateRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12=\n" +
	"\x06tokens\x18\x04 \x03(\v2%.agentspb.GenerateRequest.TokensEntryR\x06tokens\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x02R\vtemperature\x1a9\n" +
	"\vTokensEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x10GenerateResponse\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x05R\n" +
	"tokensUsed\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode2S\n" +
	"\fAgentService\x12C\n" +
	"\bGenerate\x12\x19.agentspb.GenerateRequest\x1a\x1a.agentspb.GenerateResponse\"\x00B\x0eZ\fagents/pb;pbb\x06proto3"

var (
	file_agents_proto_rawDescOnce sync.Once
	file_agents_proto_rawDescData []byte
)

func file_agents_proto_rawDescGZIP() []byte {
	file_agents_proto_rawDescOnce.Do(func() {
		file_agents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agents_proto_rawDesc), len(file_agents_proto_rawDesc)))
	})
	return file_agents_proto_rawDescData
}

var file_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_agents_proto_goTypes = []any{
	(*GenerateRequest)(nil),  // 0: agentspb.GenerateRequest
	(*GenerateResponse)(nil), // 1: agentspb.GenerateResponse
	nil,                      // 2: agentspb.GenerateRequest.TokensEntry
}
var file_agents_proto_depIdxs = []int32{
	2, // 0: agentspb.GenerateRequest.tokens:type_name -> agentspb.GenerateRequest.TokensEntry
	0, // 1: agentspb.AgentService.Generate:input_type -> agentspb.GenerateRequest
	1, // 2: agentspb.AgentService.Generate:output_type -> agentspb.GenerateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agents_proto_init() }
func file_agents_proto_init() {
	if File_agents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agents_proto_rawDesc), len(file_agents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agents_proto_goTypes,
		DependencyIndexes: file_agents_proto_depIdxs,
		MessageInfos:      file_agents_proto_msgTypes,
	}.Build()
	File_agents_proto = out.File
	file_agents_proto_goTypes = nil
	file_agents_proto_depIdxs = nil
}
