// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: proto/user-files.proto

package userfilespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserFilesService_GetProjectFiles_FullMethodName = "/userfiles.UserFilesService/GetProjectFiles"
)

// UserFilesServiceClient is the client API for UserFilesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserFilesServiceClient interface {
	GetProjectFiles(ctx context.Context, in *GetProjectFilesRequest, opts ...grpc.CallOption) (*GetProjectFilesResponse, error)
}

type userFilesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserFilesServiceClient(cc grpc.ClientConnInterface) UserFilesServiceClient {
	return &userFilesServiceClient{cc}
}

func (c *userFilesServiceClient) GetProjectFiles(ctx context.Context, in *GetProjectFilesRequest, opts ...grpc.CallOption) (*GetProjectFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectFilesResponse)
	err := c.cc.Invoke(ctx, UserFilesService_GetProjectFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserFilesServiceServer is the server API for UserFilesService service.
// All implementations must embed UnimplementedUserFilesServiceServer
// for forward compatibility.
type UserFilesServiceServer interface {
	GetProjectFiles(context.Context, *GetProjectFilesRequest) (*GetProjectFilesResponse, error)
	mustEmbedUnimplementedUserFilesServiceServer()
}

// UnimplementedUserFilesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserFilesServiceServer struct{}

func (UnimplementedUserFilesServiceServer) GetProjectFiles(context.Context, *GetProjectFilesRequest) (*GetProjectFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectFiles not implemented")
}
func (UnimplementedUserFilesServiceServer) mustEmbedUnimplementedUserFilesServiceServer() {}
func (UnimplementedUserFilesServiceServer) testEmbeddedByValue()                          {}

// UnsafeUserFilesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserFilesServiceServer will
// result in compilation errors.
type UnsafeUserFilesServiceServer interface {
	mustEmbedUnimplementedUserFilesServiceServer()
}

func RegisterUserFilesServiceServer(s grpc.ServiceRegistrar, srv UserFilesServiceServer) {
	// If the following call panics, it indicates UnimplementedUserFilesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserFilesService_ServiceDesc, srv)
}

func _UserFilesService_GetProjectFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFilesServiceServer).GetProjectFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserFilesService_GetProjectFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFilesServiceServer).GetProjectFiles(ctx, req.(*GetProjectFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserFilesService_ServiceDesc is the grpc.ServiceDesc for UserFilesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserFilesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userfiles.UserFilesService",
	HandlerType: (*UserFilesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProjectFiles",
			Handler:    _UserFilesService_GetProjectFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user-files.proto",
}
