// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/user-files.proto

package userfilespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProjectFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectFilesRequest) Reset() {
	*x = GetProjectFilesRequest{}
	mi := &file_proto_user_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectFilesRequest) ProtoMessage() {}

func (x *GetProjectFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectFilesRequest.ProtoReflect.Descriptor instead.
func (*GetProjectFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_files_proto_rawDescGZIP(), []int{0}
}

func (x *GetProjectFilesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type CodeFileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Encoding      string                 `protobuf:"bytes,4,opt,name=encoding,proto3" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeFileEntry) Reset() {
	*x = CodeFileEntry{}
	mi := &file_proto_user_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeFileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeFileEntry) ProtoMessage() {}

func (x *CodeFileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeFileEntry.ProtoReflect.Descriptor instead.
func (*CodeFileEntry) Descriptor() ([]byte, []int) {
	return file_proto_user_files_proto_rawDescGZIP(), []int{1}
}

func (x *CodeFileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CodeFileEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CodeFileEntry) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CodeFileEntry) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

type GetProjectFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Files         []*CodeFileEntry       `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	TotalFiles    int32                  `protobuf:"varint,4,opt,name=total_files,json=totalFiles,proto3" json:"total_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectFilesResponse) Reset() {
	*x = GetProjectFilesResponse{}
	mi := &file_proto_user_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectFilesResponse) ProtoMessage() {}

func (x *GetProjectFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectFilesResponse.ProtoReflect.Descriptor instead.
func (*GetProjectFilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_files_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectFilesResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetProjectFilesResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetProjectFilesResponse) GetFiles() []*CodeFileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GetProjectFilesResponse) GetTotalFiles() int32 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

var File_proto_user_files_proto protoreflect.FileDescriptor

const file_proto_user_files_proto_rawDesc = "" +
	"\n" +
	"\x16proto/user-files.proto\x12\tuserfiles\"1\n" +
	"\x16GetProjectFilesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"u\n" +
	"\rCodeFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1a\n" +
	"\bencoding\x18\x04 \x01(\tR\bencoding\"\x9c\x01\n" +
	"\x17GetProjectFilesResponse\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12.\n" +
	"\x05files\x18\x03 \x03(\v2\x18.userfiles.CodeFileEntryR\x05files\x12\x1f\n" +
	"\vtotal_files\x18\x04 \x01(\x05R\n" +
	"totalFiles2l\n" +
	"\x10UserFilesService\x12X\n" +
	"\x0fGetProjectFiles\x12!.userfiles.GetProjectFilesRequest\x1a\".userfiles.GetProjectFilesResponseB Z\x1euser/internal/grpc/userfilespbb\x06proto3"

var (
	file_proto_user_files_proto_rawDescOnce sync.Once
	file_proto_user_files_proto_rawDescData []byte
)

func file_proto_user_files_proto_rawDescGZIP() []byte {
	file_proto_user_files_proto_rawDescOnce.Do(func() {
		file_proto_user_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_files_proto_rawDesc), len(file_proto_user_files_proto_rawDesc)))
	})
	return file_proto_user_files_proto_rawDescData
}

var file_proto_user_files_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_user_files_proto_goTypes = []any{
	(*GetProjectFilesRequest)(nil),  // 0: userfiles.GetProjectFilesRequest
	(*CodeFileEntry)(nil),           // 1: userfiles.CodeFileEntry
	(*GetProjectFilesResponse)(nil), // 2: userfiles.GetProjectFilesResponse
}
var file_proto_user_files_proto_depIdxs = []int32{
	1, // 0: userfiles.GetProjectFilesResponse.files:type_name -> userfiles.CodeFileEntry
	0, // 1: userfiles.UserFilesService.GetProjectFiles:input_type -> userfiles.GetProjectFilesRequest
	2, // 2: userfiles.UserFilesService.GetProjectFiles:output_type -> userfiles.GetProjectFilesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_user_files_proto_init() }
func file_proto_user_files_proto_init() {
	if File_proto_user_files_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_files_proto_rawDesc), len(file_proto_user_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_files_proto_goTypes,
		DependencyIndexes: file_proto_user_files_proto_depIdxs,
		MessageInfos:      file_proto_user_files_proto_msgTypes,
	}.Build()
	File_proto_user_files_proto = out.File
	file_proto_user_files_proto_goTypes = nil
	file_proto_user_files_proto_depIdxs = nil
}
