// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: boss-manager.proto

package managerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagerService_AssignManager_FullMethodName               = "/manager.ManagerService/AssignManager"
	ManagerService_AssignManagersAndWait_FullMethodName       = "/manager.ManagerService/AssignManagersAndWait"
	ManagerService_AssignManagersAndWaitStream_FullMethodName = "/manager.ManagerService/AssignManagersAndWaitStream"
)

// ManagerServiceClient is the client API for ManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagerServiceClient interface {
	// Assign ONE manager — Boss вызывает для каждого менеджера отдельно
	AssignManager(ctx context.Context, in *AssignManagerRequest, opts ...grpc.CallOption) (*ManagerResult, error)
	// Assign ALL managers — Boss вызывает один раз, менеджер сам координирует
	AssignManagersAndWait(ctx context.Context, in *AssignManagersRequest, opts ...grpc.CallOption) (*AssignManagersResponse, error)
	// Streaming version - отправляет обновления по мере выполнения
	AssignManagersAndWaitStream(ctx context.Context, in *AssignManagersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskUpdate], error)
}

type managerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerServiceClient(cc grpc.ClientConnInterface) ManagerServiceClient {
	return &managerServiceClient{cc}
}

func (c *managerServiceClient) AssignManager(ctx context.Context, in *AssignManagerRequest, opts ...grpc.CallOption) (*ManagerResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManagerResult)
	err := c.cc.Invoke(ctx, ManagerService_AssignManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) AssignManagersAndWait(ctx context.Context, in *AssignManagersRequest, opts ...grpc.CallOption) (*AssignManagersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignManagersResponse)
	err := c.cc.Invoke(ctx, ManagerService_AssignManagersAndWait_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) AssignManagersAndWaitStream(ctx context.Context, in *AssignManagersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagerService_ServiceDesc.Streams[0], ManagerService_AssignManagersAndWaitStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AssignManagersRequest, TaskUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerService_AssignManagersAndWaitStreamClient = grpc.ServerStreamingClient[TaskUpdate]

// ManagerServiceServer is the server API for ManagerService service.
// All implementations must embed UnimplementedManagerServiceServer
// for forward compatibility.
type ManagerServiceServer interface {
	// Assign ONE manager — Boss вызывает для каждого менеджера отдельно
	AssignManager(context.Context, *AssignManagerRequest) (*ManagerResult, error)
	// Assign ALL managers — Boss вызывает один раз, менеджер сам координирует
	AssignManagersAndWait(context.Context, *AssignManagersRequest) (*AssignManagersResponse, error)
	// Streaming version - отправляет обновления по мере выполнения
	AssignManagersAndWaitStream(*AssignManagersRequest, grpc.ServerStreamingServer[TaskUpdate]) error
	mustEmbedUnimplementedManagerServiceServer()
}

// UnimplementedManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagerServiceServer struct{}

func (UnimplementedManagerServiceServer) AssignManager(context.Context, *AssignManagerRequest) (*ManagerResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignManager not implemented")
}
func (UnimplementedManagerServiceServer) AssignManagersAndWait(context.Context, *AssignManagersRequest) (*AssignManagersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignManagersAndWait not implemented")
}
func (UnimplementedManagerServiceServer) AssignManagersAndWaitStream(*AssignManagersRequest, grpc.ServerStreamingServer[TaskUpdate]) error {
	return status.Error(codes.Unimplemented, "method AssignManagersAndWaitStream not implemented")
}
func (UnimplementedManagerServiceServer) mustEmbedUnimplementedManagerServiceServer() {}
func (UnimplementedManagerServiceServer) testEmbeddedByValue()                        {}

// UnsafeManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerServiceServer will
// result in compilation errors.
type UnsafeManagerServiceServer interface {
	mustEmbedUnimplementedManagerServiceServer()
}

func RegisterManagerServiceServer(s grpc.ServiceRegistrar, srv ManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagerService_ServiceDesc, srv)
}

func _ManagerService_AssignManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).AssignManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_AssignManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).AssignManager(ctx, req.(*AssignManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_AssignManagersAndWait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignManagersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).AssignManagersAndWait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_AssignManagersAndWait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).AssignManagersAndWait(ctx, req.(*AssignManagersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_AssignManagersAndWaitStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AssignManagersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagerServiceServer).AssignManagersAndWaitStream(m, &grpc.GenericServerStream[AssignManagersRequest, TaskUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerService_AssignManagersAndWaitStreamServer = grpc.ServerStreamingServer[TaskUpdate]

// ManagerService_ServiceDesc is the grpc.ServiceDesc for ManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manager.ManagerService",
	HandlerType: (*ManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignManager",
			Handler:    _ManagerService_AssignManager_Handler,
		},
		{
			MethodName: "AssignManagersAndWait",
			Handler:    _ManagerService_AssignManagersAndWait_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AssignManagersAndWaitStream",
			Handler:       _ManagerService_AssignManagersAndWaitStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "boss-manager.proto",
}
