# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grade.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgrade.proto\x12\x06grader\"\x1c\n\x0cGradeRequest\x12\x0c\n\x04task\x18\x01 \x01(\t\"@\n\rGradeResponse\x12\x0c\n\x04task\x18\x01 \x01(\t\x12\x12\n\ntranslated\x18\x02 \x01(\t\x12\r\n\x05grade\x18\x03 \x01(\x05\x32\x42\n\x06Grader\x12\x38\n\tGradeTask\x12\x14.grader.GradeRequest\x1a\x15.grader.GradeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grade_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRADEREQUEST']._serialized_start=23
  _globals['_GRADEREQUEST']._serialized_end=51
  _globals['_GRADERESPONSE']._serialized_start=53
  _globals['_GRADERESPONSE']._serialized_end=117
  _globals['_GRADER']._serialized_start=119
  _globals['_GRADER']._serialized_end=185
# @@protoc_insertion_point(module_scope)
