package boss

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"

	"nodes/internal/service/git"
	gh "nodes/internal/service/github"
	"nodes/pkg/database"
	"nodes/pkg/models"
)

// pushToGitHub — создаёт репозиторий и пушит результат, если есть GITHUB_TOKEN.
// Возвращает URL созданного репозитория или пустую строку.
func (s *Service) pushToGitHub(ctx context.Context, task *models.Task, projectPath string, issueTarget *gh.IssueTarget) string {
	if os.Getenv("GITHUB_TOKEN") == "" || s.githubClient == nil {
		return ""
	}
	if task.ProjectJSON != "" {
		return task.ProjectJSON
	}
	if issueTarget != nil && issueTarget.Cloned {
		return s.createPullRequest(ctx, task, projectPath, issueTarget)
	}

	log.Printf("Pushing results to GitHub...")
	// If the repo already has an "origin" remote (cloned or refinement), push update.
	// NOTE: we check for the remote, not just .git — initGitRepo also creates .git
	// for new projects but doesn't configure a remote.
	existingRemote := extractRemoteURL(projectPath)
	if existingRemote != "" {
		repoURL := task.ProjectJSON
		if repoURL == "" {
			repoURL = existingRemote
		}
		if err := s.githubClient.PushToRepository(ctx, task, projectPath, repoURL); err != nil {
			log.Printf("Failed to push update to existing: %v", err)
			return ""
		}
		return repoURL
	}
	repoURL, err := s.githubClient.CreateRepository(ctx, task)
	if err != nil {
		log.Printf("Failed to create GitHub repository: %v", err)
		return ""
	}
	if err := s.githubClient.PushToRepository(ctx, task, projectPath, repoURL); err != nil {
		log.Printf("Failed to push to GitHub: %v", err)
		return ""
	}
	log.Printf("Successfully pushed to GitHub: %s", repoURL)
	task.ProjectJSON = repoURL
	database.Db.Save(task)
	return repoURL
}

func (s *Service) createPullRequest(ctx context.Context, task *models.Task, projectPath string, target *gh.IssueTarget) string {
	log.Printf("Creating GitHub pull request for %s/%s#%d", target.Owner, target.Repo, target.Number)
	if err := git.CheckoutBranch(projectPath, target.BranchName); err != nil {
		log.Printf("Failed to checkout pull request branch: %v", err)
		return ""
	}
	if err := s.githubClient.PushBranch(ctx, projectPath, target.BranchName); err != nil {
		log.Printf("Failed to push pull request branch: %v", err)
		return ""
	}
	pr, err := s.githubClient.CreatePullRequest(ctx, gh.PullRequestRequest{
		Owner: target.Owner,
		Repo:  target.Repo,
		Title: pullRequestTitle(task, target),
		Head:  target.BranchName,
		Base:  firstNonEmpty(target.BaseBranch, "main"),
		Body:  pullRequestBody(task, target),
	})
	if err != nil {
		log.Printf("Failed to create GitHub pull request: %v", err)
		return ""
	}
	log.Printf("Successfully created GitHub pull request: %s", pr.HTMLURL)
	task.ProjectJSON = pr.HTMLURL
	database.Db.Save(task)
	return pr.HTMLURL
}

func pullRequestTitle(task *models.Task, target *gh.IssueTarget) string {
	title := target.IssueTitle
	if title == "" {
		title = task.Title
	}
	if title == "" {
		title = "Octra generated fix"
	}
	return fmt.Sprintf("Fix #%d: %s", target.Number, title)
}

func pullRequestBody(task *models.Task, target *gh.IssueTarget) string {
	return fmt.Sprintf(`Fixes %s/%s#%d

Generated by Octra for task %s.
	`, target.Owner, target.Repo, target.Number, task.ID.String())
}

// extractRemoteURL — получает origin URL из локального .git
func extractRemoteURL(projectPath string) string {
	cmd := exec.Command("git", "-C", projectPath, "remote", "get-url", "origin")
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}
